apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-cronjob
spec:
  schedule: "0 0 * * *" # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: backend:latest
            command: ["go", "run", "main.go", "cleanup"]
            env:
            - name: DB_DSN
              value: "host=postgres user=user password=pass dbname=app port=5432 sslmode=disable"
          restartPolicy: Never
        
