apiVersion: batch/v1
kind: Job
metadata:
  name: message-analysis-job
spec:
  template:
    spec:
      containers:
      - name: analyze
        image: backend:latest
        command: ["go", "run", "main.go", "analyze"]
        env:
        - name: DB_DSN
          value: "host=postgres user=user password=pass dbname=app port=5432 sslmode=disable"
      restartPolicy: Never
        
